### PR TITLE
First pass at making `tack` context-aware.

### PR DESCRIPTION
**Pull request by ax-nathan**
The list of valid contexts are hard-coded in the root Makefile.

To select a context type `make <name>-context`, for example `make test-context`. This will create the necessary folder at ./contexts/<name> and populate with template files, which you can then modify.

With a context selected, type `make all` to bring up a new cluster for that context. Once terraform completes, you can use `kubectl` directly in the same shell.

To switch between multiple deployed contexts, rerun `make <name>-context` and kubectl will be reconfigured.

### CODE REVIEW

**Comment by ax-nathan** [comment]
@wellsie Here's my attempt at making `tack` context-aware. Seems to work well...I can create two independent cluster within the same AWS account and switch easily between them via make. I hope you like...and I'm happy to make any changes you suggest!

**Comment by wellsie** [comment]
Thanks Nathan. I've merged into a branch (ax-nathan-context) so I can play with it. Ultimately I want to move away from `make` but the main thing right now is that you are unblocked - sounds like this works for you for now.

**Comment by ax-nathan** [comment]
Hmm...why move away from `make`? I'd be curious as to your rationale...and what else you're considering?

**Comment by wellsie** [comment]
make it more of a cli tool like say `kubectl`. so it can be run anywhere. `make` locks one to a directory. it is a good place to start though. i believe kubectl started out as a shell script and evolved to a go app.

**Pull request closed without merging**
