### PR TITLE
Add ability to manage multiple clusters via "contexts"

### PR DESCRIPTION
**Pull request by ax-nathan**
No code here yet, but created this PR to explore adding the ability to manage multiple clusters via "contexts".

### CODE REVIEW

**Comment by wellsie** [comment]
Hey Nathan. It is close to being able to handle multiple contexts. Planning to use `var.name` as part of the context name. Also want to write some preflight checks for execution prior to running `terraform apply` to ensure that the context doesn't already exists and fail with message if it does. Looking into that this week.

**Comment by ax-nathan** [comment]
OK. Any plans to include Terraform remote state in the implementation? I need both multiple contexts and remote state pronto, so I may go ahead and take a crack at it on my branch... If we both end up with working solutions, then I don't care what lives on long-term, but I've got to push forward. I hope you don't mind!

**Comment by ax-nathan** [comment]
Also, as I wasn't clear before... I intend for the "context" concern to include both Terraform and Kubernetes under the same name in a 1:1 relationship.

**Comment by wellsie** [comment]
yep - want to do remote state for sure. 

i don’t mind at all nathan.

if i understand correctly you need to be able to bang out multiple independent clusters under the same AWS account asap. thus the need for context and remote state, right ?

**Comment by ax-nathan** [comment]
Yup. Exactly right.

On Monday, March 14, 2016, Jono Wells notifications@github.com wrote:

> yep - want to do remote state for sure.
> 
> i don’t mind at all nathan.
> 
> if i understand correctly you need to be able to bang out multiple
> independent clusters under the same AWS account asap. thus the need for
> context and remote state, right ?
> 
> > On Mar 14, 2016, at 10:17 AM, ax-nathan <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > 
> > OK. Any plans to include Terraform remote state in the implementation? I
> > need both multiple contexts and remote state pronto, so I may go ahead and
> > take a crack at it on my branch... If we both end up with working
> > solutions, then I don't care what lives on long-term, but I've got to push
> > forward. I hope you don't mind!
> > 
> > —
> > Reply to this email directly or view it on GitHub <
> > https://github.com/kz8s/tack/pull/3#issuecomment-196419472>.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kz8s/tack/pull/3#issuecomment-196451144.

## 

_Nathan Probst_
nathan@actourex.com
970.402.7384

**Comment by wellsie** [comment]
cool. i’m looking at context now. in fact the `CLUSTER_NAME = testingg` ‘typo’ was a part of the effort to de-hard-code the ‘testing’ references throughout :)

i think that what is left for context is:
1) preflight check before commencing initial build to ensure that the context doesn’t exist - right now i just overwrite the context every time
2) pass `var.name` into the context creation template

i’ve been dragging my feet on 1) - haven’t worked out the _right_ time to assert the context doesn’t exist yet.

**Pull request merged**
