### PR TITLE
Allow kubernetes master to handle security groups for kubectl expose

### PR DESCRIPTION
**Pull request by zaheerm**

### CODE REVIEW

**Comment by tomfotherby** [comment]
Is there any reason why this PR isn't being merged? It is needed by everyone who tries `tack.` 

With the greatest respect, what are the plans for this project? It's been 2 months since the last merge, is it now shelved? I'm very grateful for all the work done so far, it's helped us enormously, but if the project is shelved it might be best to be transparent about it.

**Comment by bruj0** [comment]
The last news from @wellsie was that he was working on a rehaul on a private branch and that was last month.

I think at this point we can assume its not longer maintained or at least not in this repository.

@wellsie if you re reading this, are you ok with somebody or multiple people taking over maintenance of the project?

**Comment by dileepfrog** [comment]
@zaheerm Thank you for this!

**Comment by zaheerm** [comment]
@dileepfrog you're welcome, hopefully it can be merged here

**Review by wellsie — APPROVED** [review]

**Pull request merged**
